version: '3'
services:
  app:
    restart: always
    build: .
    container_name: 'app'
    tty: true
    volumes:
      - ./:/app/
  db:
    image: mariadb
    volumes:
      - ./sql:/var/lib/mysql
    ports:
        - "13306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password!
