FROM python:3.11.0-slim-bullseye

WORKDIR /app/

RUN pip install --upgrade pip

RUN apt-get update

RUN apt-get install -y libxml2-dev libxslt-dev libmariadb-dev libfreetype6-dev gcc

COPY ./requirements.txt /app/requirements.txt

RUN pip install -r /app/requirements.txt
